name: redeo_app
description: "A payment management solution for Educational Officers"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  image_picker: ^1.0.4  # For profile picture uploads
  url_launcher: ^6.2.1  # For support links
  package_info_plus: ^8.3.0  # For app version info
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets section
  assets:
    - assets/icons/
    - assets/icons/payment/